# We create a dictionnary to define the size of each logo
size_dictionnary = {
    "ANA": {"sizex": 13, "sizey": 13},
    "ARI": {"sizex": 13, "sizey": 13},
    "BOS": {"sizex": 12, "sizey": 12},
    "BUF": {"sizex": 12, "sizey": 12},
    "CAR": {"sizex": 19, "sizey": 19},
    "CBJ": {"sizex": 12, "sizey": 12},
    "CGY": {"sizex": 12, "sizey": 12},
    "CHI": {"sizex": 15, "sizey": 15},
    "COL": {"sizex": 16, "sizey": 16},
    "DAL": {"sizex": 13, "sizey": 13},
    "DET": {"sizex": 18, "sizey": 18},
    "EDM": {"sizex": 13, "sizey": 13},
    "FLA": {"sizex": 15, "sizey": 15},
    "LAK": {"sizex": 15, "sizey": 15},
    "MIN": {"sizex": 18, "sizey": 18},
    "MTL": {"sizex": 11, "sizey": 11},
    "NJD": {"sizex": 13, "sizey": 13},
    "NSH": {"sizex": 18, "sizey": 18},
    "NYI": {"sizex": 14, "sizey": 14},
    "NYR": {"sizex": 15, "sizey": 15},
    "OTT": {"sizex": 13, "sizey": 13},
    "PHI": {"sizex": 16, "sizey": 16},
    "PIT": {"sizex": 16, "sizey": 16},
    "SEA": {"sizex": 13, "sizey": 13},
    "SJS": {"sizex": 17, "sizey": 17},
    "STL": {"sizex": 12, "sizey": 12},
    "TBL": {"sizex": 13, "sizey": 13},
    "TOR": {"sizex": 16, "sizey": 16},
    "VAN": {"sizex": 13, "sizey": 13},
    "VGK": {"sizex": 15, "sizey": 15},
    "WPG": {"sizex": 15, "sizey": 15},
    "WSH": {"sizex": 22, "sizey": 22},
}